version: "3"

services:
  # cli:
  #   image: whywebs/cli:1.0


  

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whywebs
      MYSQL_USER: root
      MYSQL_PASSWORD: root
 

  
  redis:
    image: redis:latest
    build: ./whywebs-drupal/redis

  nginx:
    image: nginx
    build: ./whywebs-drupal/nginx
    volumes:
     - ./nginx:/etc/nginx/conf.d/nginx
    ports:
     - "1010:1010"
    environment:
     - NGINX_HOST=nginx.whywebs.dev
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  drush:
    image: drush/drush
    build: ./whywebs-drupal/drush 

  web:
    build: ./whywebs-drupal
    restart: always
    volumes:
      - ./public:/var/www/html
    links:
     - mariadb
     - mariadb:database
     - redis
    ports:
      - 9090:80
    networks:
      whywebs.dev:
 
  jenkins:
    container_name: jenkins
    restart: always
    build: ./whywebs-drupal/jenkins
    ports:
      - "4040:4040"
    volumes:
      - ./jenkins:/var/jenkins_home 
    networks:
      whywebs.dev:
         aliases:
          - jenkins.whywebs.dev

networks:
    whywebs.dev:
      driver: bridge

volumes:
  public:

