version: "2"

services:
  mariadb:
    image: whywebs/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: whywebs
      MYSQL_DATABASE: whywebs_drupal_docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
   # Images with WhyWebs Drupal – whywebs/WhyWebsDockerDrupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: whywebs/WhyWebsDockerDrupal:7-7.1-2.1.2
#    image: whywebs/WhyWebsDockerDrupal:7-7.0-2.1.2
     image: whywebs/WhyWebsDockerDrupal:7-5.6-2.1.2
#    image: whywebs/WhyWebsDockerDrupal:8-7.1-2.1.2
#    image: whywebs/WhyWebsDockerDrupal:8-7.0-2.1.2

   # Images without Drupal – whywebs/WhyWebsDockerDrupal-php:[PHP_VERSION]-[STABILITY_TAG].
#    image: whywebs/WhyWebsDockerDrupal-php:7.1-2.1.0
#    image: whywebs/WhyWebsDockerDrupal-php:7.0-2.1.0
#    image: whywebs/WhyWebsDockerDrupal-php:5.6-2.1.0
#    image: whywebs/WhyWebsDockerDrupal-php:5.3-2.1.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: whywebs_guest
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - codebase:/var/www/html
#      - docker-sync-unison:/var/www/html # Docker-sync for macOS users

  nginx:
  # whywebs/WhyWebsDockerDrupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: whywebs/WhyWebsDockerDrupal-nginx:8-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - codebase:/var/www/html
#      - docker-sync-unison:/var/www/html # Docker-sync for macOS users
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:whywebs.docker.localhost'

 varnish:
   image: whywebs/WhyWebsDockerDrupal-varnish:4.1-2.1.0
   depends_on:
     - nginx
   environment:
     VARNISH_SECRET: secret
     VARNISH_BACKEND_HOST: nginx
     VARNISH_BACKEND_PORT: 80
   labels:
     - 'traefik.backend=varnish'
     - 'traefik.port=6081'
     - 'traefik.frontend.rule=Host:varnish.whywebs.docker.localhost'

 redis:
   image: whywebs/redis:3.2-2.1.0

 pma:
   image: phpmyadmin/phpmyadmin
   environment:
     PMA_HOST: mariadb
     PMA_USER: root
     PMA_PASSWORD: root
     PHP_UPLOAD_MAX_FILESIZE: 1G
     PHP_MAX_INPUT_VARS: 1G
   labels:
     - 'traefik.backend=pma'
     - 'traefik.port=80'
     - 'traefik.frontend.rule=Host:pma.whywebs.docker.localhost'

 solr:
# whywebs/WhyWebsDockerDrupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
     image: whywebs/WhyWebsDockerDrupal-solr:8-6.4-2.0.0
#    image: whywebs/WhyWebsDockerDrupal-solr:8-6.3-2.0.0
#    image: whywebs/WhyWebsDockerDrupal-solr:8-5.5-2.0.0
#    image: whywebs/WhyWebsDockerDrupal-solr:7-6.4-2.0.0
#    image: whywebs/WhyWebsDockerDrupal-solr:7-6.3-2.0.0
#    image: whywebs/WhyWebsDockerDrupal-solr:7-5.5-2.0.0
   environment:
     SOLR_HEAP: 1024m
   labels:
     - 'traefik.backend=solr'
     - 'traefik.port=8983'
     - 'traefik.frontend.rule=Host:solr.whywebs.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.whywebs.docker.localhost'

#  node:
#    image: node:7-alpine
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.whywebs.docker.localhost'
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    image: whywebs/memcached:1.4-2.0.0

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Docker-sync for macOS users
volumes:
 docker-sync-unison:
   external: true

# volumes:
#   codebase:


  # Enjoy your whywebs drupal docker