version: "2"

services:
  
  mariadb:
    image: mariadb:latest
    container_name: m_whywebs
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: whywebs
      MYSQL_DATABASE: whywebs
      MYSQL_USER: whywebs
      MYSQL_PASSWORD: whywebs
      MYSQL_HOST: localhost
    volumes:
      # Use a "volume" to prevent data from disappearing when the container is
      # restarted.
      - /var/lib/mysql
      # In a production setting, you'd use a locally mounted volume for extra
      # persistence.  This would mount ./data to /var/lib/mysql inside the container:
      # - ./data:/var/lib/mysql
  
  varnish:
    # A public image with a Varnish install
    image: jacksoncage/varnish
    # Pass backend connections to the linked "web" container
    environment:
      VARNISH_BACKEND_IP: web
    # Set up the internal link
    links:
      - web:web
    # Expose port 8100 on the host.
    ports:
      - 8100:80

  jenkins:
    container_name: j_whywebs
    image: whywebs/jenkins:latest
    ports:
      - "4040:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home 
    stdin_open: true
    tty: true

  solr:
    # Example of extending a container with our own Dockerfile
    build: ./whywebs-drupal/solr
    image: whywebs/solr:latest
    # Expose port 8983 directly on the host
    ports:
      - 8983:8983
  #
  # Drush
  #
  drush:

    # Comment this and uncomment 'build' below if you want to edit your
    # local dockerfile and build from there. This is useful for development
    image: drush/drush:8-php5
    volumes:
      - ./config/drush:/home/root/.drush
    environment:
      COLUMNS: 150
      DOMAIN: whwyebs.dev
      HOME: /home/root
      HOSTNAME: whywebs.dev
      MYSQL_HOST: mariadb
      TERM: xterm
    stdin_open: true
    tty: true

  web:
    build: ./
    image: whywebs/drupal7:latest
    container_name: web_whywebs
    volumes:
      # Mount the local drupal directory in the container
      - ./deploy:/var/www/html
      - ./whywebscli.sh:/var/www/html/whywebscli.sh
    ports:
    # Expose port 8101 on the host.  Useful for debugging w/o Varnish
    - "8080:80"
    links:
      # Link the Solr container:
      - solr:solr
      # Link the mariaDB container:
      - mariadb:mariadb
      - jenkins:jenkins
    environment:
     - WHYWEBS_DB=whywebs
     - WHYWEBS_PASS=whywebs
     - WHYWEBS_USER=whywebs
     - WHYWEBS_HOST=localhost
     - WHYWEBS_HOST=whywebs.local
     - WHYWEBS_PORT=80

  # nginx:
  #   build: ./whywebs-drupal/nginx
  #   image: whywebs/nginx:latest
  #   container_name: n_whywebs
  #   volumes:
  #    - ./deploy:/etc/nginx
  #    - ./config/drupal.conf:/etc/nginx/conf.d/drupal.conf
  #    - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
  #   ports:
  #    - "1010:1010"
  #   environment:
  #    - NGINX_HOST=nginx.whywebs.dev
  #    - NGINX_PORT=1010