version: "3"

services:
  # cli:
  #   image: whywebs/cli:1.0
  #
  # This defines a data container to share common Platform.sh app assets such as:
  #
  data:
    image: busybox
    volumes:
      - /certs
      - /var/lib/mysql
      - /code
      - /php

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whywebs
      MYSQL_USER: whywebsdrupal
      MYSQL_PASSWORD: root

  web:
    image: php:5.6.30-apache
    ports:
      - "9090:80"
      - "whywebs.site:8080:80"
    hostname: whywebslocal
    domainname: whywebs.dev
    links:
     - mariadb
     - mariadb:database
     - redis
    volumes:
      - ./public:/var/www/html
    hostname: whywebs
    environment:
      DOMAIN: whywebs.dev
      HOSTNAME: whywebslocal
      HOME: ./public:/var/www/html
      MYSQL_HOST: mariadb

  app:
    image: busybox

  redis:
    image: redis:latest

  # nginx:
  #   image: nginx
  #     volumes:
  #      - ./nginx:/etc/nginx/conf.d/nginx
  #     ports:
  #      - "1010:80"
  #     environment:
  #      - NGINX_HOST=nginx.whywebs.dev
  #      - NGINX_PORT=80
  #     command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  
  drush:
    image: drush/drush
