language: php

sudo: required

services:
  - docker

env:
  global:
    - LATEST_DRUPAL=8
    - LATEST_SOLR=6.4
  matrix:
    - DRUPAL=7 SOLR=5.4
    - DRUPAL=7 SOLR=5.5
    - DRUPAL=7 SOLR=6.3
    - DRUPAL=7 SOLR=6.4
    - DRUPAL=8 SOLR=5.5
    - DRUPAL=8 SOLR=6.3
    - DRUPAL=8 SOLR=6.4

script:
  - cd ./$DRUPAL/$SOLR
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$DRUPAL-$SOLR-$TRAVIS_TAG" release
    fi

    if [ "$DRUPAL" == "$LATEST_DRUPAL" && "$SOLR" == "$LATEST_SOLR" ]; then
      make VERSION=latest release
    fi
  fi

after_failure:
  - docker logs solr
