version: "2"

services:
  mariadb:
    image: $MARIADB
    environment:
       MYSQL_ROOT_PASSWORD: whywebs
      MYSQL_DATABASE: whywebs_drupal_docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    image: $DRUPAL8_PHP71
    environment:
      # To skip auto init.
      DRUPAL_VERSION: 8
      DB_HOST: mariadb
      DB_NAME: drupal
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_DRIVER: mysql
      PHP_SENDMAIL_PATH: '/bin/true'
    volumes:
      - codebase:/var/www/html
      - ./test.sh:/var/www/html/test.sh
      - ./test.settings.php:/var/www/html/web/sites/default/test.settings.php
      - ./varnish-purger.yml:/var/www/html/web/varnish-purger.yml
      - ./search-api-solr-server.yml:/var/www/html/web/search-api-solr-server.yml

  nginx:
    image: $DRUPAL8_NGINX
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - codebase:/var/www/html
    depends_on:
      - php

  varnish:
    image: $DRUPAL_VARNISH
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
      VARNISH_MEMORY_SIZE: 256M
      VARNISH_STORAGE_SIZE: 1024M

  redis:
    image: $REDIS

  solr:
    image: $DRUPAL8_SOLR
    environment:
      SOLR_HEAP: 1024m

volumes:
  codebase:
