language: php

sudo: required

services:
  - docker

env:
  global:
    - REPO=whywebs/whywebsdockerdrupal/tree/master/whywebs-drupal-mariadb
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - docker build -t $REPO:$COMMIT ./
  - docker run -d --name=mariadb -e "MYSQL_RANDOM_ROOT_PASSWORD=1" -e "MYSQL_DATABASE=drupal" -e "MYSQL_USER=drupal" -e "MYSQL_PASSWORD=drupal" $REPO:$COMMIT

script:
  - docker ps | grep -q "$REPO:$COMMIT"
  - |
    for i in {30..0}; do
      if docker exec mariadb mysql -udrupal -pdrupal -e "SELECT 1;" &> /dev/null; then
        break
      fi
      echo 'MySQL init process in progress...'
      sleep 1
    done
  - docker exec mariadb mysql -udrupal -pdrupal -e "SHOW DATABASES;" | grep "drupal"

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker tag $REPO:$COMMIT $REPO:latest;

    if [ -n "$TRAVIS_TAG" ]; then docker tag $REPO:$COMMIT $REPO:$TRAVIS_TAG; fi

    docker rmi $REPO:$COMMIT
    docker push $REPO
  fi

after_failure:
  - docker logs mariadb